version: '3'

services:
  sensitivity_annotation_app:
    container_name: sensitivity_annotation_app
    build: .
    volumes:
      - ./logs:/var/log/uwsgi
    command: bash -c "uwsgi --ini wsgi-conf.ini"
    ports:
      - 8000:8000
    deploy:
        resources:
            limits:
                memory: 16G
    networks:
      backend:
        aliases:
          - sensitivity_annotation_app

  # web_server:
  #   container_name: nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./logs:/etc/nginx/logs
  #   depends_on:
  #     - sensitivity_annotation_app
  #   ports:
  #     - 80:80
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
